// src/client/src/app/auth/login/login.component.ts
import { Component, OnInit } from "@angular/core";
import { AuthService } from "../auth.service";
import { Router } from "@angular/router";
import { AlertService } from "src/app/services/alert.service";

@Component({
  selector: "app-login",
  templateUrl: "./login.component.html",
  styleUrls: ["./login.component.scss"],
})
export class LoginComponent implements OnInit {
  username: any;
  password: any;

  loading: any;

  constructor(
    private authService: AuthService,
    private alertService: AlertService,
    private router: Router
  ) {}

  ngOnInit() {}

  login() {
    console.log(this.username, this.password);
    this.loading = true;
    this.authService.login(this.username, this.password).subscribe(
      (res: any) => {
        this.loading = false;
        this.alertService.showMessage("Logged In Successfully", false);

        localStorage.setItem("isUserLoggedIn", "true");
        localStorage.setItem("username", res.username);
        localStorage.setItem("userId", res.userId);
        localStorage.setItem("name", res.name);
        localStorage.setItem("email", res.email);
        localStorage.setItem("token", res.token);
        this.authService.userLoggedIn = true;
        this.router.navigateByUrl("/dashboard");
      },
      (err) => {
        this.loading = false;
      }
    );
  }
}

<div class="login-section">
  <div class="columns">
    <div class="column"></div>
    <div class="column is-half">
      <div class="card">
        <section class="hero is-warning">
          <div class="hero-body">
            <div class="container">
              <h1 class="title">Login</h1>
              <h2 class="subtitle">Start splitting your bills!!</h2>
            </div>
          </div>
        </section>
        <div class="card-content">
          <div class="content">
            <form (ngSubmit)="login()">
              <div class="field">
                <label class="label">Username</label>
                <div class="control has-icons-left has-icons-right">
                  <input
                    name="username"
                    id="username"
                    class="input"
                    type="text"
                    placeholder="Enter your username"
                    [(ngModel)]="username"
                  />
                  <span class="icon is-small is-left">
                    <i class="fas fa-user"></i>
                  </span>
                </div>
              </div>
              <div class="field">
                <label class="label">Password</label>
                <div class="control has-icons-left has-icons-right">
                  <input
                    name="password"
                    id="password"
                    class="input"
                    type="password"
                    placeholder="Enter your password"
                    [(ngModel)]="password"
                  />
                  <span class="icon is-small is-left">
                    <i class="fas fa-key"></i>
                  </span>
                </div>
              </div>

              <div class="field is-grouped">
                <div class="control">
                  <button
                    [ngClass]="{ 'is-loading': loading }"
                    [disabled]="
                      !username ||
                      !password ||
                      username.trim().length == 0 ||
                      password.trim().length == 0
                    "
                    class="button is-link is-medium"
                  >
                    Login
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <div class="column"></div>
  </div>
</div>

// src/client/src/views/Login.vue
<template>
  <div class="login">
    <div>
      <div
        class="uk-card uk-card-default uk-card-hover uk-card-body uk-align-center uk-animation-scale-up"
      >
        <div class="uk-card-header">
          <div class="uk-grid-small uk-flex-middle" uk-grid>
            <div class="uk-width-expand">
              <h3 class="uk-card-title uk-margin-remove-bottom">Login</h3>
              <p>Split your bills now!</p>
            </div>
          </div>
        </div>

        <div class="uk-card-body">
          <div v-if="showError" class="uk-alert-danger" uk-alert>
            <p>{{ errorMessage }}</p>
          </div>

          <form class="uk-form-stacked uk-dark uk-align-center">
            <div class="uk-margin">
              <label class="uk-form-label" for="form-stacked-text">Username</label>
              <div class="uk-form-controls uk-inline uk-width-1-1">
                <span class="uk-form-icon" uk-icon="icon: user"></span>
                <input
                  v-model="username"
                  class="uk-input uk-width-1-1"
                  type="text"
                  placeholder="Enter your username"
                />
              </div>
            </div>

            <div class="uk-margin">
              <label class="uk-form-label" for="form-stacked-text">Password</label>
              <div class="uk-form-controls uk-width-1-1 uk-inline">
                <span class="uk-form-icon" uk-icon="icon: lock"></span>
                <input
                  v-model="password"
                  class="uk-input uk-width-1-1"
                  type="password"
                  placeholder="Enter your password"
                />
              </div>
            </div>
          </form>

          <button
            @click="login"
            class="uk-button uk-button-large uk-button-primary uk-align-center"
          >Login</button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { mutations } from "../store/store";
import { logIn } from "../API";

export default {
  name: "Login",
  data() {
    return {
      username: "",
      password: "",
      showError: false,
      errorMessage: ""
    };
  },
  methods: {
    async login() {
      this.showError = false;
      this.errorMessage = "";

      const user = {
        username: this.username,
        password: this.password
      };

      console.log(user);

      const response = await logIn(user);

      response.json().then(json => {
        if (json.error) {
          this.showError = true;
          this.errorMessage = json.error;
        } else {
          console.log(json);
          // Set Local Storage
          mutations.setLoggedIn(true);
          localStorage.setItem("isUserLoggedIn", "true");
          localStorage.setItem("username", json.username);
          localStorage.setItem("userId", json.userId);
          localStorage.setItem("name", json.name);
          localStorage.setItem("email", json.email);
          localStorage.setItem("token", json.token);
          mutations.setUser({
            userId: localStorage.getItem("userId"),
            username: localStorage.getItem("username"),
            name: localStorage.getItem("name"),
            email: localStorage.getItem("email")
          });
          this.$router.push("/dashboard");
        }
      });
    }
  }
};
</script>

<style lang="scss">
.uk-card {
  width: 25rem;
  max-width: 90vw;
}
.login-section {
  align-content: center;
}
</style>
