// src/client/src/app/auth/signup/signup.component.ts
import { Component, OnInit } from "@angular/core";
import { AuthService } from "../auth.service";
import { FormGroup, FormControl, Validators } from "@angular/forms";
import { AlertService } from "src/app/services/alert.service";
import { Router } from "@angular/router";

@Component({
  selector: "app-signup",
  templateUrl: "./signup.component.html",
  styleUrls: ["./signup.component.scss"],
})
export class SignupComponent implements OnInit {
  signupForm: FormGroup;
  loading: any;
  formSubmitted: boolean;

  constructor(
    private authService: AuthService,
    private alertService: AlertService,
    private router: Router
  ) {}

  ngOnInit() {
    this.signupForm = new FormGroup({
      name: new FormControl(null, [
        Validators.required,
        Validators.minLength(4),
      ]),
      username: new FormControl(null, [
        Validators.required,
        Validators.minLength(4),
      ]),
      email: new FormControl(null, [
        Validators.required,
        Validators.email,
        Validators.minLength(4),
      ]),
      password: new FormControl(null, [
        Validators.required,
        Validators.minLength(8),
      ]),
      confirmPassword: new FormControl(null, [
        Validators.required,
        Validators.minLength(8),
      ]),
    });
  }

  signup() {
    this.formSubmitted = true;
    console.log(this.signupForm.value);
    if (this.signupForm.invalid) {
      return;
    }
    if (
      this.signupForm.value.password != this.signupForm.value.confirmPassword
    ) {
      this.alertService.showMessage("Passwords must match", true);
      return;
    }
    this.loading = true;
    this.authService.signup(this.signupForm.value).subscribe(
      (res: any) => {
        this.loading = false;
        this.alertService.showMessage("Signed Up In Successfully", false);

        this.router.navigateByUrl("/login");
      },
      (err) => {
        this.loading = false;
      }
    );
  }
}

<div class="login-section">
  <div class="columns">
    <div class="column"></div>
    <div class="column is-half">
      <div class="card">
        <section class="hero is-warning">
          <div class="hero-body">
            <div class="container">
              <h1 class="title">Signup</h1>
              <h2 class="subtitle">Get Started splitting bills!</h2>
            </div>
          </div>
        </section>
        <div class="card-content">
          <div class="content">
            <form [formGroup]="signupForm" (ngSubmit)="signup()">
              <div class="field">
                <label class="label">Name</label>
                <div class="control has-icons-left has-icons-right">
                  <input
                    [ngClass]="{
                      'is-danger':
                        signupForm.controls.name.dirty &&
                        signupForm.controls.name.errors
                    }"
                    name="name"
                    id="name"
                    class="input"
                    type="text"
                    placeholder="Enter your name"
                    formControlName="name"
                  />
                  <span class="icon is-small is-left">
                    <i class="fas fa-user-circle"></i>
                  </span>
                  <p
                    *ngIf="
                      signupForm.controls.name.dirty &&
                      signupForm.controls.name.errors?.required
                    "
                    class="help is-danger"
                  >
                    Name is required.
                  </p>
                  <p
                    *ngIf="
                      signupForm.controls.name.dirty &&
                      signupForm.controls.name.errors?.minlength
                    "
                    class="help is-danger"
                  >
                    Name at least have 4 characters.
                  </p>
                </div>
              </div>
              <div class="field">
                <label class="label">Email</label>
                <div class="control has-icons-left has-icons-right">
                  <input
                    [ngClass]="{
                      'is-danger':
                        signupForm.controls.email.dirty &&
                        signupForm.controls.email.errors
                    }"
                    name="email"
                    id="email"
                    class="input"
                    type="email"
                    placeholder="Enter your email"
                    formControlName="email"
                  />
                  <span class="icon is-small is-left">
                    <i class="fas fa-envelope"></i>
                  </span>
                  <p
                    *ngIf="
                      signupForm.controls.email.dirty &&
                      signupForm.controls.email.errors?.required
                    "
                    class="help is-danger"
                  >
                    Email is required.
                  </p>
                  <p
                    *ngIf="
                      signupForm.controls.email.dirty &&
                      signupForm.controls.email.errors?.email
                    "
                    class="help is-danger"
                  >
                    Email is Invalid
                  </p>
                </div>
              </div>
              <div class="field">
                <label class="label">Username</label>
                <div class="control has-icons-left has-icons-right">
                  <input
                    [ngClass]="{
                      'is-danger':
                        signupForm.controls.username.dirty &&
                        signupForm.controls.username.errors
                    }"
                    name="username"
                    id="username"
                    class="input"
                    type="text"
                    placeholder="Choose your username"
                    formControlName="username"
                  />
                  <span class="icon is-small is-left">
                    <i class="fas fa-user"></i>
                  </span>
                  <p
                    *ngIf="
                      signupForm.controls.username.dirty &&
                      signupForm.controls.username.errors?.required
                    "
                    class="help is-danger"
                  >
                    Username is required.
                  </p>
                  <p
                    *ngIf="
                      signupForm.controls.username.dirty &&
                      signupForm.controls.username.errors?.minlength
                    "
                    class="help is-danger"
                  >
                    Username at least have 4 characters.
                  </p>
                </div>
              </div>
              <div class="field">
                <label class="label">Password</label>
                <div class="control has-icons-left has-icons-right">
                  <input
                    [ngClass]="{
                      'is-danger':
                        signupForm.controls.password.dirty &&
                        signupForm.controls.password.errors
                    }"
                    name="password"
                    id="password"
                    class="input"
                    type="password"
                    placeholder="Choose your password"
                    formControlName="password"
                  />
                  <span class="icon is-small is-left">
                    <i class="fas fa-key"></i>
                  </span>
                  <p
                    *ngIf="
                      signupForm.controls.password.dirty &&
                      signupForm.controls.password.errors?.required
                    "
                    class="help is-danger"
                  >
                    Password is required.
                  </p>
                  <p
                    *ngIf="
                      signupForm.controls.password.dirty &&
                      signupForm.controls.password.errors?.minlength
                    "
                    class="help is-danger"
                  >
                    Password at least have 8 characters.
                  </p>
                </div>
              </div>
              <div class="field">
                <label class="label">Confirm Password</label>
                <div class="control has-icons-left has-icons-right">
                  <input
                    [ngClass]="{
                      'is-danger':
                        signupForm.controls.confirmPassword.dirty &&
                        signupForm.controls.confirmPassword.errors
                    }"
                    name="password"
                    id="password"
                    class="input"
                    type="password"
                    placeholder="Re-enter your password"
                    formControlName="confirmPassword"
                  />
                  <span class="icon is-small is-left">
                    <i class="fas fa-key"></i>
                  </span>
                  <p
                    *ngIf="
                      signupForm.controls.confirmPassword.dirty &&
                      signupForm.controls.confirmPassword.errors?.required
                    "
                    class="help is-danger"
                  >
                    Confirm Password is required.
                  </p>
                  <p
                    *ngIf="
                      signupForm.controls.confirmPassword.dirty &&
                      signupForm.controls.confirmPassword.errors?.minlength
                    "
                    class="help is-danger"
                  >
                    Confirm Password at least have 8 characters.
                  </p>
                </div>
              </div>

              <div class="field is-grouped">
                <div class="control">
                  <button
                    [disabled]="formSubmitted && signupForm.invalid"
                    [ngClass]="{ 'is-loading': loading }"
                    class="button is-link is-medium"
                  >
                    Signup
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <div class="column"></div>
  </div>
</div>

// src/client/src/views/Signup.vue
<template>
  <div class="signup">
    <div>
      <div
        class="uk-card uk-card-default uk-card-hover uk-card-body uk-align-center uk-animation-scale-up"
      >
        <div class="uk-card-header">
          <div class="uk-grid-small uk-flex-middle" uk-grid>
            <div class="uk-width-expand">
              <h3 class="uk-card-title uk-margin-remove-bottom">Signup</h3>
              <p>Start Spliting bills now!</p>
            </div>
          </div>
        </div>

        <div class="uk-card-body">
          <div v-if="showError" class="uk-alert-danger" uk-alert>
            <p>{{ errorMessage }}</p>
          </div>

          <form class="uk-form-stacked uk-dark uk-align-center">
            <div class="uk-margin">
              <label class="uk-form-label" for="form-stacked-text">Name</label>
              <div class="uk-form-controls uk-inline uk-width-1-1">
                <span class="uk-form-icon" uk-icon="icon: pencil"></span>
                <input
                  :class="{
                    'uk-form-danger':
                      (!$v.name.required || !$v.name.minLength) &&
                      formSubmitted,
                  }"
                  v-model.trim="$v.name.$model"
                  class="uk-input uk-width-1-1"
                  type="text"
                  placeholder="Enter your name"
                />
              </div>
              <small
                class="error-text uk-form-help-block"
                v-if="!$v.name.required && formSubmitted"
              >Name is required</small>
              <small
                class="error-text uk-form-help-block"
                v-if="!$v.name.minLength && formSubmitted"
              >Name should have at least 4 characters</small>
            </div>

            <div class="uk-margin">
              <label class="uk-form-label" for="form-stacked-text">Email</label>
              <div class="uk-form-controls uk-inline uk-width-1-1">
                <span class="uk-form-icon" uk-icon="icon: mail"></span>
                <input
                  :class="{
                    'uk-form-danger':
                      (!$v.email.required || !$v.email.email) && formSubmitted,
                  }"
                  v-model.trim="$v.email.$model"
                  class="uk-input uk-width-1-1"
                  type="email"
                  placeholder="Enter your email"
                />
              </div>
              <small
                class="error-text uk-form-help-block"
                v-if="!$v.email.required && formSubmitted"
              >Email is required</small>
              <small
                class="error-text uk-form-help-block"
                v-if="!$v.email.email && formSubmitted"
              >Invalid email format</small>
            </div>

            <div class="uk-margin">
              <label class="uk-form-label" for="form-stacked-text">Username</label>
              <div class="uk-form-controls uk-inline uk-width-1-1">
                <span class="uk-form-icon" uk-icon="icon: user"></span>
                <input
                  :class="{
                    'uk-form-danger':
                      (!$v.username.required || !$v.username.minLength) &&
                      formSubmitted,
                  }"
                  v-model.trim="$v.username.$model"
                  class="uk-input uk-width-1-1"
                  type="text"
                  placeholder="Enter your username"
                />
              </div>
              <small
                class="error-text uk-form-help-block"
                v-if="!$v.username.required && formSubmitted"
              >Username is required</small>
              <small
                class="error-text uk-form-help-block"
                v-if="!$v.username.minLength && formSubmitted"
              >Username should have at least 4 characters</small>
            </div>

            <div class="uk-margin">
              <label class="uk-form-label" for="form-stacked-text">Password</label>
              <div class="uk-form-controls uk-width-1-1 uk-inline">
                <span class="uk-form-icon" uk-icon="icon: lock"></span>
                <input
                  :class="{
                    'uk-form-danger':
                      (!$v.password.required || !$v.password.minLength) &&
                      formSubmitted,
                  }"
                  v-model.trim="$v.password.$model"
                  class="uk-input uk-width-1-1"
                  type="password"
                  placeholder="Enter your password"
                />
              </div>
              <small
                class="error-text uk-form-help-block"
                v-if="!$v.password.required && formSubmitted"
              >Password is required</small>
              <small
                class="error-text uk-form-help-block"
                v-if="!$v.password.minLength && formSubmitted"
              >Password should have at least 8 characters</small>
            </div>

            <div class="uk-margin">
              <label class="uk-form-label" for="form-stacked-text">Confirm Password</label>
              <div class="uk-form-controls uk-width-1-1 uk-inline">
                <span class="uk-form-icon" uk-icon="icon: lock"></span>
                <input
                  :class="{
                    'uk-form-danger':
                      (!$v.confirmPassword.required ||
                        !$v.confirmPassword.minLength ||
                        !$v.confirmPassword.sameAsPassword) &&
                      formSubmitted,
                  }"
                  v-model.trim="$v.confirmPassword.$model"
                  class="uk-input uk-width-1-1"
                  type="password"
                  placeholder="Re-Enter your password"
                />
              </div>
              <small
                class="error-text uk-form-help-block"
                v-if="!$v.confirmPassword.required && formSubmitted"
              >Password is required</small>
              <small
                class="error-text uk-form-help-block"
                v-if="!$v.confirmPassword.minLength && formSubmitted"
              >Password should have at least 8 characters</small>
              <small
                class="error-text uk-form-help-block"
                v-if="!$v.confirmPassword.sameAsPassword && formSubmitted"
              >Passwords does not match</small>
            </div>
          </form>

          <button
            @click="signup"
            class="uk-button uk-button-large uk-button-primary uk-align-center"
          >Sign Up</button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { required, minLength, sameAs, email } from "vuelidate/lib/validators";
import { signUp } from "../API";

export default {
  name: "Login",
  data() {
    return {
      name: "",
      email: "",
      username: "",
      password: "",
      confirmPassword: "",
      showError: false,
      errorMessage: "",
      formSubmitted: false
    };
  },
  validations: {
    name: {
      required,
      minLength: minLength(4)
    },
    username: {
      required,
      minLength: minLength(4)
    },
    email: {
      required,
      email
    },
    password: {
      required,
      minLength: minLength(8)
    },
    confirmPassword: {
      required,
      minLength: minLength(8),
      sameAsPassword: sameAs("password")
    }
  },
  methods: {
    async signup() {
      this.formSubmitted = true;
      this.showError = false;
      this.errorMessage = "";

      this.$v.$touch();

      if (this.$v.$invalid) {
        return;
      }

      if (this.password != this.confirmPassword) {
        this.showError = true;
        this.errorMessage = "Passwords does not match";
        return;
      }

      const user = {
        username: this.username,
        name: this.name,
        email: this.email,
        password: this.password,
        friends: []
      };

      console.log(user);

      const response = await signUp(user);

      if (response) {
        response.json().then(json => {
          if (json.error) {
            this.showError = true;
            this.errorMessage = json.message;
          } else {
            console.log(json);
            this.$router.push("/login");
          }
        });
      }
    }
  }
};
</script>

<style lang="scss">
.uk-card {
  width: 25rem;
  max-width: 90vw;
}
.signup-section {
  align-content: center;
}
.error-text {
  color: red;
  display: block;
}
</style>
